---
- name: Install Nomad from Official Repository
  hosts: all
  become: yes
  tasks:
    - name: Install Pre-Requisite Packages 
      apt:
        name: [ 
          wget, 
          gpg, 
          cgroup-tools
        ]
        state: present

    - name: Add HashiCorp GPG Key
      ansible.builtin.shell: |
        wget -O - https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add HashiCorp Repository
      ansible.builtin.apt_repository:
        repo: deb [arch=arm64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com bookworm main
        state: present
        filename: hashicorp

    - name: Install Nomad
      apt:
        name: nomad-enterprise
        state: present
        
- name: Configure Nomad Server Nodes
  hosts: nomad_servers
  become: yes
  tasks:
    - name: Remove Packaged nomad.hcl File From Nomad Configuration Directory
      file:
        path: /etc/nomad.d/nomad.hcl
        state: absent

    - name: Remove client.hcl Files From Nomad Configuration Directory If Switching Persona
      file:
        path: /etc/nomad.d/client.hcl
        state: absent

    - name: Remove Docker From Server Nodes If Present
      apt:
        name: docker-ce
        state: absent

    - name: Remove Required Packages For Docker If Present
      apt:
        name: [ 
          apt-transport-https, 
          ca-certificates, 
          curl, 
          gnupg, 
          lsb-release
        ]
        state: absent

    - name: Remove Docker Repository If Present
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Remove Docker GPG Key If Present
      file:
        path: /usr/share/keyrings/docker-archive-keyring.gpg
        state: absent

    - name: Create Nomad Server License File
      copy:
        src: licenses/nomad/license.hclic
        dest: /etc/nomad.d/license.hclic
        owner: nomad
        group: nomad

    - name: Create Nomad Server Configuration File
      template:
        src: configs/nomad/server.hcl
        dest: /etc/nomad.d/server.hcl
        owner: nomad
        group: nomad
      notify: Restart Nomad Service

  handlers:
    - name: Restart Nomad Service
      systemd:
        name: nomad
        state: restarted

- name: Configure Nomad Client Nodes
  hosts: nomad_clients
  become: yes
  tasks:
    - name: Install Required Packages For Docker
      apt:
        name: [ 
          apt-transport-https, 
          ca-certificates, 
          curl, 
          gnupg, 
          lsb-release
        ]
        state: present

    - name: Add Docker GPG Key
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb [arch={{ 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
        state: present
        filename: docker

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Add User to Docker Group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Remove Packaged nomad.hcl Files From Nomad Configuration Directory
      file:
        path: /etc/nomad.d/nomad.hcl
        state: absent

    - name: Remove server.hcl Files From Nomad Configuration Directory If Switching Persona
      file:
        path: /etc/nomad.d/server.hcl
        state: absent

    - name: Create Nomad Client Configuration File
      template:
        src: configs/nomad/client.hcl
        dest: /etc/nomad.d/client.hcl
        owner: nomad
        group: nomad
      notify: Restart Nomad Service

  handlers:
    - name: Restart Nomad Service
      systemd:
        name: nomad
        state: restarted